"""empty message

Revision ID: 3cbef0a6fecb
Revises: 
Create Date: 2020-07-03 01:42:47.613778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3cbef0a6fecb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job', sa.Column('date_posted', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('is_confirmed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_confirmed')
    op.drop_column('job', 'date_posted')
    # ### end Alembic commands ###
